In [2]:
import duckdb

duckdb.sql("""
    SELECT *
    FROM parquet_scan('../data/silver/crashes/v1/full/run_date=*/*.parquet')
    LIMIT 10
""").df()

,unique_id,collision_id,crash_date,crash_time,pre_crash,travel_direction,point_of_impact,contributing_factor_1,contributing_factor_2,crash_year,run_date
0,20364177,4594551,2023-01-01,09:23,Parked,East,Left Front Quarter Panel,Unspecified,Unspecified,2023,2026-03-03
1,20364825,4594751,2023-01-01,13:38,Making Left Turn,West,NaN,Unsafe Speed,NaN,2023,2026-03-03
2,20364178,4594551,2023-01-01,09:23,Parked,East,Left Rear Bumper,Unspecified,Unspecified,2023,2026-03-03
3,20369709,4597028,2023-01-01,20:55,Parked,South,Left Rear Bumper,Unspecified,Unspecified,2023,2026-03-03
4,20364064,4594437,2023-01-01,04:25,Going Straight Ahead,North,Right Rear Quarter Panel,Driver Inattention/Distraction,Driver Inattention/Distraction,2023,2026-03-03
5,20365312,4595216,2023-01-01,09:45,Stopped in Traffic,East,Center Back End,Unspecified,Unspecified,2023,2026-03-03
6,20364170,4594641,2023-01-01,08:45,Parked,South,Center Front End,Unspecified,Unspecified,2023,2026-03-03
7,20364800,4594775,2023-01-01,00:55,Slowing or Stopping,East,Left Front Quarter Panel,Alcohol Involvement,Alcohol Involvement,2023,2026-03-03
8,20364787,4594752,2023-01-01,17:00,Going Straight Ahead,North,Right Front Bumper,Passing or Lane Usage Improper,Unspecified,2023,2026-03-03
9,20365342,4595088,2023-01-01,10:16,Backing,Southeast,Center Back End,Backing Unsafely,Unspecified,2023,2026-03-03

In [3]:
import duckdb

duckdb.sql("""
    SELECT *
    FROM parquet_scan('../data/silver_quarantine/crashes/v1/full/run_date=*/*.parquet')
    LIMIT 10
""").df()

Empty DataFrame
Columns: [unique_id, collision_id, crash_date, crash_time, pre_crash, travel_direction, point_of_impact, contributing_factor_1, contributing_factor_2, crash_year, dq_reasons, run_date]
Index: []