In [2]:
import duckdb

duckdb.sql("""
    SELECT *
    FROM parquet_scan('../data/gold/fact/fact_crash/run_date=*/*.parquet')
    LIMIT 10
""").df()

,collision_id,date_key,crash_date,crash_time,number_of_persons_injured,number_of_persons_killed,number_of_pedestrians_injured,number_of_pedestrians_killed,number_of_cyclist_injured,number_of_cyclist_killed,number_of_motorist_injured,number_of_motorist_killed,total_vehicles,total_occupants,run_date
0,4599014,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,0,2026-03-06
1,4598137,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,3,3,2026-03-06
2,4599015,20230101,2023-01-01,None,1,0,1,0,0,0,0,0,1,1,2026-03-06
3,4599499,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,2,1,2026-03-06
4,4599239,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,2,3,2026-03-06
5,4599214,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,0,2026-03-06
6,4599827,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,0,2026-03-06
7,4600461,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,2,2026-03-06
8,4600840,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,0,2026-03-06
9,4600946,20230101,2023-01-01,None,0,0,0,0,0,0,0,0,1,0,2026-03-06

In [6]:
import duckdb

duckdb.sql("""
    SELECT *
    FROM parquet_scan('../data/gold/dim/dim_vehicle/*.parquet')
    LIMIT 10
""").df()

,vehicle_dim_id,vehicle_make,vehicle_type
0,38718848805153,(1 AXLE TRAILER),TRAILER
1,95348558475317,(MTA BUS) ARTIC NEW FLYER,BUS
2,151001204194191,-CAR/SUV,STATION WAGON/SPORT UTILITY VEHICLE
3,35539618936576,/GMC,TK
4,95659472624777,15 NOVA,BUS
5,279315944441657,150,MOPED
6,279016545238151,150,MOTORCYCLE
7,2802027766685,1500,PICK-UP TRUCK
8,197871803196619,18 WHEELER,VAN
9,13427844164159,18 WHEELER TRUCK,BULK AGRICULTURE